### ISSUE TITLE
Unable to manage teams

### ISSUE THREAD

**Issue by andrewweakland** [TheNAF/naflm#56] opened 2015-12-02 15:14 UTC
I'm unable to delete teams in my league, even though the have not yet had a match scheduled. (I'm the admin of NYCBBL)

![naf obblm bug](https://cloud.githubusercontent.com/assets/16119321/11534616/89c343ee-98dd-11e5-86b8-725f475a37e9.png)

**Comment by williamleonard** [comment] 2015-12-03 01:10
This looks like it may have always been an issue.  The problem is that the COACH:: mayManageObj() method is using the coach id to check the league id of the team that you are trying to delete.  I see that the admin page sends the coach id if it is a coach object and for the team obj it sends the owned by coach id.  So either way it sends a coach id.

I edited the ./admin/admin_ct_man.php page on thenafdev.obblm.com with the following and it works.  I am also going to email Nicholas to see if he agrees.  It seems like it was a mistake.

        #WHL if (!$coach->mayManageObj($IS_COACH ? T_OBJ_COACH : T_OBJ_TEAM, $IS_COACH ? $o->coach_id : $o->owned_by_coach_id)) {
             if (!$coach->mayManageObj($IS_COACH ? T_OBJ_COACH : T_OBJ_TEAM, $IS_COACH ? $o->coach_id : $id)) {



Test it out and let me know if you find any issues with it.  I deleted test2, btw.

**Comment by Shteve0** [comment] 2015-12-03 01:18
Andrew has local commissioner permissions. Are we sure this is an issue not a feature request?

**Comment by andrewweakland** [comment] 2015-12-03 04:04
I'm now able to delete my own teams as well as my players who are helping
to test. Seems to be working well.

**Comment by williamleonard** [comment] 2015-12-04 00:47
I committed this change.
df0ec5c241e3ecc0ba20c6a22453377c8895f84d

**Closed by williamleonard** 2015-12-04 00:47 UTC

**Comment by nicholasmr** [comment] 2015-12-06 21:28
Sorry for the late response Will. Looks good.
