### ISSUE TITLE
Mobile: Changes Team TVs for match

### ISSUE THREAD

**Issue by hutchinsfairy** [TheNAF/naflm#77] opened 2016-02-11 09:34 UTC
If I edit a match using the mobile interface it seems to change the team TVs on the match page.

Recreate:
1) Schedule a match on desktop site - Current team TVs shown on match page
2) Edit the match using mobile interface and save (I edited score and gave player a Cmp)
3) View match page in desktop site and TVs are zeroed

I also then changed TVs to 4 on desktop site and then saved on mobile site and they changed to 4000!

I may not be running the most up-to-date version so sorry if it's already fixed!

**Comment by rythos42** [comment] 2016-02-11 17:56
Big thanks for the report! These kinds of things give me the willies...overwriting existing data. >.<

**Comment by rythos42** [comment] 2016-02-11 19:00
The first thing was an easy fix. The second I have some questions about.

(1) The TVs were coming back from the server as strings like "4000", which the mobile JS code divided by 1000 in order to use. "4000"/1000 isn't a number, because it's a string. Did a parseInt before using the numbers.

(2) So I can see how it *might* end up multiplied by 1000, but I couldn't reproduce it. The saving code (in both mobile and desktop) multiplies the users input by 1000 before saving to the database. So if something messed up in there, I could see it coming out as 4000. But I could get the steps right -- could you try again and let me know what I'm missing?

**Comment by hutchinsfairy** [comment] 2016-02-12 13:12
Recreation steps for me:

Desktop:
1) login as coach
2) Schedule match
3) View match (TVs correct)
4) Set both TVs to 4 and save
Mobile:
5) Open match
6) Change both scores and gice a completion to player #1
7) Click save
Desktop:
8) View match report

**Comment by rythos42** [comment] 2016-03-04 00:54
21 days later...

I looked at this locally and using your repro steps it isn't happening. I assume that I fixed it with the earlier fix to this issue. I'm going to close this issue after a bit -- if you get a chance to try the newest code and see if you can repro it, let me know!

**Comment by rythos42** [comment] 2016-03-07 18:46
Going to close this, as I believe it is fixed.

**Closed by rythos42** 2016-03-07 18:46 UTC
Labels: bug, high priority

**Comment by hutchinsfairy** [comment] 2016-03-08 21:22
Sorry for the late response, haven't had a chance to update my repo and test. I'll reopen if I find anything but it doesn't seem likely.
