### ISSUE TITLE
Problems with installation.

### ISSUE THREAD

**Issue by bhimebaugh** [TheNAF/naflm#188] opened 2016-12-22 00:46 UTC
Hello!

I'm installing a clean version of the NAFLM 1.0.  I've setup the SQL DB and User, I've made sure the settings.php has been updated to reflect the correct information (DB, username, password).

When I go to the initial Install.php, it has the button for the SETUP DB for OBBLM, however it has a notice prior to that:

Notice: Undefined variable: argv in /home/uhearttr/public_html/mtbbl/install.php on line 30

When I click on the Setup DB button, it then runs to a 404 error page:

Not Found
The requested URL /install.php was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

The file is still there - it does create a DB, though all the tables are empty with no listings of anything.

Any ideas?

**Comment by Shteve0** [comment] 2017-02-01 00:11
Have you tried /mtbbl/install.php?

**Comment by bhimebaugh** [comment] 2017-07-30 20:23
I had tried that, now I'm onto a different problem:

It appears to have created the site, but when I go to the main page I get the following:


Warning: ksort() expects parameter 1 to be array, null given in /home/uhearttr/public_html/testpbbl/lib/misc_functions.php on line 126

Warning: Invalid argument supplied for foreach() in /home/uhearttr/public_html/testpbbl/lib/class_translations.php on line 87

Warning: Invalid argument supplied for foreach() in /home/uhearttr/public_html/testpbbl/lib/class_translations.php on line 97

All at the top of the screen.  This is after using the most current release from github.

**Comment by mfranchetti** [comment] 2017-09-12 15:43
I'm seeing the same error message on a clean install from release 1.0 and from the current NAFLM Master.
`Notice: Undefined variable: argv in /home/uhearttr/public_html/mtbbl/install.php on line 30`
It doesn't seem to impact the install in any way that I can identify if ignored.
Looking back, the variable argv was added in a commit on 6th June 2013 by funnyfingers [https://github.com/TheNAF/naflm/commit/d79e50c6b0bf034a31aea1a8f27cf43ccae740cc#diff-3b7de2cf163f18aa521c050bb543084f](url)
argv seems to be a standard variable name used in a variety of places. I suspect it may be checking to see if SETUP has been passed in as a parameter on the URL. Can probably be fixed by checking to see if it exists first.
Wondering if the issue has existed since 2013 or if a more recent change has stopped argv from being created causing the error?

**Comment by williamleonard** [comment] 2017-09-12 15:58
Argv is used for command line installations.  The notice probably always existed since I added it.  If you want to wrap it in a check to avoid the notice that is fine, but definitely keep the functionality.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mfranchetti** [comment] 2017-09-12 16:18
Ah, that makes sense. I'll wrap it in a check.
`if (isset($_POST['setup']) || (isset($argv[1]) ? $argv[1] == 'setup' : false)) {`

**Comment by mfranchetti** [comment] 2018-02-14 16:45
Realised the 404 issue was caused by installing OBBLM to a subdirectory as Steve highlighted above.
Closing the issue.

**Closed** 2018-02-14 16:45 UTC
Labels: Bug, High Priority
